In [2]:
import numpy as np

## Numpy array

In [3]:
myList = [20,30,40]

In [4]:
type(myList)

list

In [5]:
np.array(myList) #numpy dizisi

array([20, 30, 40])

In [6]:
type(np.array(myList))

numpy.ndarray

In [7]:
matrixList = [ [10,20,30], [20,30,40], [30,40,50] ]


In [8]:
matrixList[1]

[20, 30, 40]

In [9]:
np.array(matrixList)

array([[10, 20, 30],
       [20, 30, 40],
       [30, 40, 50]])

## Arange

In [10]:
range(0,10)

range(0, 10)

In [11]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [12]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

## Zeros & Ones

In [14]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [15]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [16]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [17]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

## Linspace

In [18]:
# Belirttiğimiz numaralar arasında eşit olarak boyutlandırılmış aralık bırakılmış dizi oluşturuyor

In [19]:
np.linspace(0,20,5) #0 ile 20 arasında rastgele 5 sayı seç ve aralarında eşit boşluk olsun

array([ 0.,  5., 10., 15., 20.])

In [20]:
np.linspace(0,100,4) #stop sayısı dahil ediliyor

array([  0.        ,  33.33333333,  66.66666667, 100.        ])

## Eye

In [21]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Random

In [22]:
#belirteceğimiz özelliklerde rastgele değerler oluşturmak için kullanılır

In [23]:
np.random.randn(4) #numpy dizisi döndürüyor 

array([ 1.43942966, -1.36736635, -0.42686347,  1.69677281])

In [24]:
np.random.randn(4,4)

array([[-0.40429439,  0.8371031 , -1.31744556, -0.38182798],
       [-1.34233053, -0.69908437, -2.13909385, -0.2446997 ],
       [ 0.65061658, -0.19905539,  0.34107198,  0.61213739],
       [-0.69800897,  1.2952089 ,  1.07471715, -1.17423584]])

In [25]:
np.random.randint(1,100) #tek değer döndürmek için ve integer döndürür.parantez içinde yazan rakamlar arasında döndürür.3. rakamı yazarsak yazdırılacak rakam sayısı olur

9

In [26]:
np.random.randint(1,300,5)

array([177, 297, 100, 213, 116])

In [27]:
myNumpyList = np.arange(30)
myNumpyList

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [28]:
myRandomList = np.random.randint(0,100,20)
myRandomList

array([85,  7, 78, 36,  8, 53, 11,  3,  1, 67, 63, 89, 95, 55, 61, 98, 18,
        8, 88,  2])

## Numpy Dizi Metodları

In [29]:
myNumpyList.reshape(6,5) ## bir diziyi matrise çevirmek için kullanıırız ve dizinin orjinalini bozmaz.

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [30]:
myRandomList.max()

98

In [31]:
myRandomList.min()

1

In [32]:
myRandomList.argmax()

15

In [33]:
myRandomList.argmin()

8

In [34]:
myNumpyList.shape

(30,)

In [35]:
myNumpyList

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [36]:
myRandomList

array([85,  7, 78, 36,  8, 53, 11,  3,  1, 67, 63, 89, 95, 55, 61, 98, 18,
        8, 88,  2])