In [2]:
import numpy as np

In [3]:
benimDizim = np.arange(0,15)

In [4]:
benimDizim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [5]:
benimDizim[5]

5

In [6]:
benimDizim[3:5]

array([3, 4])

In [7]:
benimDizim[2:7] #başlama indexini alır fakat bitiş indeksini almaz

array([2, 3, 4, 5, 6])

In [8]:
benimDizim[3:8] = -5 #direkt elemanları değiştirir

In [15]:
benimDizim

array([ 0,  1,  2, -5, -5, -5, -5, -5,  8,  9, 10, 11, 12, 13, 14])

In [18]:
baskaDizi = np.arange(0,24)
baskaDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [27]:
slicingDizi = baskaDizi[4:9]

In [28]:
slicingDizi

array([4, 5, 6, 7, 8])

In [29]:
baskaDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [25]:
#slicingDizi = 700
slicingDizi

700

In [26]:
type(slicingDizi)

int

In [30]:
type(slicingDizi)

numpy.ndarray

In [32]:
slicingDizi[:] = 700
slicingDizi

array([700, 700, 700, 700, 700])

In [33]:
baskaDizi

array([  0,   1,   2,   3, 700, 700, 700, 700, 700,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

In [ ]:
#orjinal diziyi değiştirmemesi için kopya oluşturmak gerekiyor

In [37]:
ornekDizi = np.arange(0,24)

In [38]:
ornekDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [39]:
ornekDiziKopyası = ornekDizi.copy ()

In [40]:
ornekDiziKopyası

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [41]:
ornekDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [42]:
ornekDiziKopyasıSlicing = ornekDiziKopyası[3:6]

In [43]:
ornekDiziKopyasıSlicing[:] = 800

In [44]:
ornekDiziKopyasıSlicing

array([800, 800, 800])

In [45]:
ornekDiziKopyası

array([  0,   1,   2, 800, 800, 800,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

In [46]:
ornekDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

## Matrix

In [ ]:
benim

In [ ]:
ornekMatrixDizisi = np.array()