In [5]:
import numpy as np

In [6]:
myList = [ [10,20,30],[20,30,40],[40,50,60] ]

In [7]:
myMatrixSeries = np.array(myList)

In [8]:
myMatrixSeries

array([[10, 20, 30],
       [20, 30, 40],
       [40, 50, 60]])

In [9]:
myMatrixSeries[0]

array([10, 20, 30])

In [10]:
myMatrixSeries[1][2]

40

In [11]:
myMatrixSeries[1,2]

40

In [14]:
myMatrixSeries[:,2] # 2. kolonu getirmek için

array([30, 40, 60])

In [15]:
yeniListe = [[0,1,2,3,4],[5,6,7,8,9],[10,11,12,13,14],[15,16,17,18,19],[20,21,22,23,24]]

In [16]:
yeniMatrix = np.array(yeniListe)

In [17]:
yeniMatrix

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [18]:
yeniMatrix[[0,2,4]]

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24]])

In [19]:
yeniMatrix[[2,4,0]]

array([[10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [ 0,  1,  2,  3,  4]])