## Operation

In [2]:
import numpy as np

In [3]:
yeniDizi = np.random.randint (1,100,20)

In [4]:
yeniDizi

array([78,  7, 46, 64, 96, 59, 24, 25, 23, 40, 30, 53, 46, 75, 72, 24, 14,
       25, 99, 60])

In [5]:
yeniDizi > 24

array([ True, False,  True,  True,  True,  True, False,  True, False,
        True,  True,  True,  True,  True,  True, False, False,  True,
        True,  True])

In [6]:
yeniDizi

array([78,  7, 46, 64, 96, 59, 24, 25, 23, 40, 30, 53, 46, 75, 72, 24, 14,
       25, 99, 60])

In [7]:
sonucDizi = yeniDizi > 24
sonucDizi

array([ True, False,  True,  True,  True,  True, False,  True, False,
        True,  True,  True,  True,  True,  True, False, False,  True,
        True,  True])

In [8]:
yeniDizi

array([78,  7, 46, 64, 96, 59, 24, 25, 23, 40, 30, 53, 46, 75, 72, 24, 14,
       25, 99, 60])

In [9]:
yeniDizi[sonucDizi] #sadece 24 ten büyük sayıların olduğu diziyi yazdırır

array([78, 46, 64, 96, 59, 25, 40, 30, 53, 46, 75, 72, 25, 99, 60])

In [10]:
yeniDizi

array([78,  7, 46, 64, 96, 59, 24, 25, 23, 40, 30, 53, 46, 75, 72, 24, 14,
       25, 99, 60])

In [11]:
yeniDizi[yeniDizi >24] # bir diziyi filtrelemek istersek gayet rahat yapabiliriz bu yöntemle

array([78, 46, 64, 96, 59, 25, 40, 30, 53, 46, 75, 72, 25, 99, 60])

In [12]:
sonDizi = np.arange (0,24)

In [13]:
sonDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [14]:
sonDizi + sonDizi

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46])

In [15]:
sonDizi *sonDizi

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529])

In [16]:
sonDizi-sonDizi

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [17]:
sonDizi / sonDizi #dizinin içinde 0 olduğu için böyle bir hata mesajı yazar fakat işlemleri yapar

<ipython-input-17-7967e2e610ee>:1: RuntimeWarning: invalid value encountered in true_divide
  sonDizi / sonDizi #dizinin içinde 0 olduğu için böyle bir hata mesajı yazar fakat işlemleri yapar


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [18]:
np.sqrt(sonDizi)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595, 4.58257569, 4.69041576, 4.79583152])

In [19]:
np.max(sonDizi)

23

In [20]:
np.min(sonDizi)

0